import os
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_report(
    score,
    category,
    skill_score,
    text_similarity,
    experience_score,
    matched,
    missing,
    suggestions,
    recommended_jobs
):
    """
    Generate the ATS analysis PDF and return its file path.
    """

    # Ensure the reports folder exists before writing the PDF.
    os.makedirs("reports", exist_ok=True)

    file_path = os.path.join("reports", "ATS_Report.pdf")

    pdf = SimpleDocTemplate(file_path)

    styles = getSampleStyleSheet()

    story = []

    # Report header

    story.append(
        Paragraph("<b><font size=20>ATS Resume Evaluator</font></b>",
                  styles["Title"])
    )

    story.append(
        Paragraph("ATS Resume Analysis Report", styles["Heading2"])
    )

    story.append(Spacer(1, 20))

    # Summary scores

    score_table = [

        ["ATS Score", f"{score}%"],

        ["Category", category],

        ["Skill Score", f"{skill_score}%"],

        ["Text Similarity", f"{text_similarity}%"],

        ["Experience Score", f"{experience_score}%"]

    ]

    table = Table(score_table)

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # Skills found in both the resume and job description.

    story.append(
        Paragraph("<b>Matched Skills</b>", styles["Heading2"])
    )

    if matched:

        for skill in matched:

            story.append(
                Paragraph(f"✔ {skill}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No matched skills found.", styles["Normal"])
        )

    story.append(Spacer(1, 20))

    # Skills requested by the job description but missing from the resume.

    story.append(
        Paragraph("<b>Missing Skills</b>", styles["Heading2"])
    )

    if missing:

        for skill in missing:

            story.append(
                Paragraph(f"✘ {skill}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No missing skills.", styles["Normal"])
        )

    story.append(Spacer(1, 20))

    # Improvement suggestions based on the match result.

    story.append(
        Paragraph("<b>Suggestions</b>", styles["Heading2"])
    )

    if suggestions:

        for item in suggestions:

            story.append(
                Paragraph(f"• {item}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No suggestions available.", styles["Normal"])
        )

    story.append(Spacer(1, 20))

    # Job roles ranked by skill overlap.

    story.append(
        Paragraph("<b>Recommended Jobs</b>", styles["Heading2"])
    )

    if recommended_jobs:

        job_table = [["Job Role", "Match Score"]]

        for job in recommended_jobs:

            job_table.append([
                job["job"],
                f'{job["score"]}%'
            ])

        table = Table(job_table)

        table.setStyle(TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ]))

        story.append(table)

    else:

        story.append(
            Paragraph("No recommendations available.", styles["Normal"])
        )

    story.append(Spacer(1, 30))

    # Footer

    story.append(
        Paragraph(
            "<b>Generated by ATS Resume Evaluator</b>",
            styles["Italic"]
        )
    )

    pdf.build(story)

    return file_path
