"""
ResumeIQ — Stage 9.6 Production-Quality PDF Report Generator

Generates a multi-page, professionally typeset PDF report using ReportLab.
Includes:
  - ResumeIQ branding header/footer with page numbers
  - ATS Score Summary (50% Skill + 30% Text + 20% Experience)
  - Matched, Missing, and Partial/Related skills
  - Gap Analysis with prioritized improvement roadmap
  - Recommendations and AI roadmap when available
  - Safe multi-page layout with KeepTogether guards
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    KeepTogether,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import HRFlowable

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
BRAND_NAME = "ResumeIQ"
REPORT_SUBTITLE = "Professional ATS Resume Analysis Report"
REPORT_FILE_PATH = os.path.join("reports", "ATS_Report.pdf")

# Palette
PRIMARY_COLOR = colors.HexColor("#1d4ed8")
PRIMARY_DARK = colors.HexColor("#1e3a8a")
ACCENT_SUCCESS = colors.HexColor("#16a34a")
ACCENT_WARNING = colors.HexColor("#d97706")
ACCENT_DANGER = colors.HexColor("#dc2626")
ACCENT_LOW = colors.HexColor("#6b7280")
TEXT_COLOR = colors.HexColor("#172033")
MUTED_COLOR = colors.HexColor("#64748b")
BORDER_COLOR = colors.HexColor("#dbe3ef")
SURFACE_COLOR = colors.HexColor("#f8fafc")
SURFACE_ALT = colors.HexColor("#f1f5f9")
HEADER_BG = colors.HexColor("#1e3a8a")

PAGE_W, PAGE_H = letter
LEFT_MARGIN = RIGHT_MARGIN = 0.65 * inch
TOP_MARGIN = BOTTOM_MARGIN = 0.65 * inch
CONTENT_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN


# ---------------------------------------------------------------------------
# Skill formatter
# ---------------------------------------------------------------------------
SKILL_MAP = {
    "aws": "AWS",
    "gcp": "GCP",
    "api": "API",
    "rest api": "REST API",
    "html": "HTML",
    "css": "CSS",
    "sql": "SQL",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "github": "GitHub",
    "git": "Git",
    "oop": "OOP",
    "dsa": "DSA",
    "nlp": "NLP",
    "natural language processing": "Natural Language Processing",
    "ai": "AI",
    "ml": "ML",
    "c++": "C++",
    "power bi": "Power BI",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "react.js": "React.js",
    "vue.js": "Vue.js",
    "node.js": "Node.js",
    "ci cd": "CI/CD",
    "ci/cd": "CI/CD",
    "devops": "DevOps",
}


def format_skill(skill):
    """Return a display-formatted version of a canonical skill name."""
    if not skill:
        return ""
    if " or " in skill:
        return " or ".join(format_skill(part) for part in skill.split(" or "))
    return SKILL_MAP.get(skill.strip().lower(), skill.strip().title())


# ---------------------------------------------------------------------------
# Page canvas callbacks (header / footer)
# ---------------------------------------------------------------------------
def _draw_header_footer(canvas, doc):
    """Draw branding header and page-number footer on every page."""
    canvas.saveState()
    page_num = doc.page

    # --- Header bar ---
    canvas.setFillColor(HEADER_BG)
    canvas.rect(0, PAGE_H - 36, PAGE_W, 36, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 13)
    canvas.setFillColor(colors.white)
    canvas.drawString(LEFT_MARGIN, PAGE_H - 24, BRAND_NAME)
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#93c5fd"))
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, PAGE_H - 24, REPORT_SUBTITLE)

    # --- Footer divider ---
    canvas.setStrokeColor(BORDER_COLOR)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, 40, PAGE_W - RIGHT_MARGIN, 40)

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED_COLOR)
    canvas.drawString(LEFT_MARGIN, 26,
                      f"Generated by {BRAND_NAME} | {datetime.now().strftime('%d %b %Y')}")
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, 26, f"Page {page_num}")

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Style factory
# ---------------------------------------------------------------------------
def _build_styles():
    """Return a dictionary of named ParagraphStyles."""
    base = getSampleStyleSheet()

    styles = {}

    styles["report_title"] = ParagraphStyle(
        "report_title",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=PRIMARY_COLOR,
        leading=26,
        spaceAfter=4,
    )
    styles["report_subtitle"] = ParagraphStyle(
        "report_subtitle",
        fontName="Helvetica",
        fontSize=10,
        textColor=MUTED_COLOR,
        leading=14,
        spaceAfter=12,
    )
    styles["section_heading"] = ParagraphStyle(
        "section_heading",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=PRIMARY_DARK,
        leading=16,
        spaceBefore=14,
        spaceAfter=6,
        borderPad=(0, 0, 2, 0),
    )
    styles["normal"] = ParagraphStyle(
        "normal",
        fontName="Helvetica",
        fontSize=10,
        textColor=TEXT_COLOR,
        leading=15,
        spaceAfter=2,
    )
    styles["muted"] = ParagraphStyle(
        "muted",
        fontName="Helvetica",
        fontSize=9,
        textColor=MUTED_COLOR,
        leading=13,
        spaceAfter=2,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet",
        fontName="Helvetica",
        fontSize=10,
        textColor=TEXT_COLOR,
        leading=14,
        leftIndent=12,
        spaceAfter=3,
    )
    styles["badge_high"] = ParagraphStyle(
        "badge_high",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=ACCENT_DANGER,
        leading=10,
    )
    styles["badge_medium"] = ParagraphStyle(
        "badge_medium",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=ACCENT_WARNING,
        leading=10,
    )
    styles["badge_low"] = ParagraphStyle(
        "badge_low",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=ACCENT_LOW,
        leading=10,
    )
    styles["ai_body"] = ParagraphStyle(
        "ai_body",
        fontName="Helvetica-Oblique",
        fontSize=9,
        textColor=MUTED_COLOR,
        leading=13,
        leftIndent=12,
        spaceAfter=3,
    )
    return styles


# ---------------------------------------------------------------------------
# Table helpers
# ---------------------------------------------------------------------------
def _score_table(score, category, skill_score, text_similarity, experience_score):
    """Two-column score summary table."""
    data = [
        ["Metric", "Value"],
        ["Overall ATS Score", f"{score:.1f}%"],
        ["Category", category],
        ["Skill Match (50%)", f"{skill_score:.1f}%"],
        ["Text Similarity (30%)", f"{text_similarity:.1f}%"],
        ["Experience Match (20%)", f"{experience_score:.1f}%"],
    ]
    col_w = [2.8 * inch, 2.4 * inch]
    t = Table(data, colWidths=col_w, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_COLOR),
        ("BACKGROUND", (0, 2), (-1, 2), SURFACE_COLOR),
        ("BACKGROUND", (0, 4), (-1, 4), SURFACE_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        # Highlight ATS score row
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (0, 1), 10),
        ("TEXTCOLOR", (1, 1), (1, 1), PRIMARY_COLOR),
        ("FONTSIZE", (1, 1), (1, 1), 13),
    ]))
    return t


def _skills_table(skills, empty_text):
    """Render a compact single-column skills list table."""
    if not skills:
        return None
    data = [[format_skill(s)] for s in skills]
    col_w = [CONTENT_WIDTH]
    t = Table(data, colWidths=col_w, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER_COLOR),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, SURFACE_COLOR]),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    return t


def _partial_skills_table(partial_matches):
    """Two-column table for partial/related skills."""
    if not partial_matches:
        return None
    data = [["Required Skill", "Candidate Skill (Related)"]]
    for p in partial_matches:
        req = format_skill(p.get("required_skill", ""))
        cand = format_skill(p.get("candidate_skill", ""))
        data.append([req, cand])
    col_w = [CONTENT_WIDTH * 0.48, CONTENT_WIDTH * 0.52]
    t = Table(data, colWidths=col_w, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT_WARNING),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE_COLOR]),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    return t


def _roadmap_table(gaps, priority_label, bg_color, text_col):
    """Render one roadmap tier as a table."""
    if not gaps:
        return None
    data = [["Skill", "Status", "Impact", "Recommendation"]]
    for g in gaps:
        skill = format_skill(g.get("skill", ""))
        status = g.get("status", "").upper()
        impact = g.get("estimated_impact", "").upper()
        rec = g.get("recommendation", "")
        data.append([skill, status, impact, Paragraph(rec, ParagraphStyle(
            "rec_cell",
            fontName="Helvetica",
            fontSize=8,
            textColor=TEXT_COLOR,
            leading=11,
        ))])
    col_w = [1.3 * inch, 0.7 * inch, 0.65 * inch, CONTENT_WIDTH - 2.65 * inch]
    t = Table(data, colWidths=col_w, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER_COLOR),
        ("BACKGROUND", (0, 0), (-1, 0), bg_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), text_col),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (2, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (2, -1), 9),
        ("TEXTCOLOR", (0, 1), (2, -1), TEXT_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE_ALT]),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    return t


def _jobs_table(recommended_jobs):
    """Recommended jobs table."""
    if not recommended_jobs:
        return None
    data = [["Job Role", "Match Score"]]
    for job in recommended_jobs:
        data.append([job.get("job", ""), f'{job.get("score", 0)}%'])
    col_w = [CONTENT_WIDTH * 0.72, CONTENT_WIDTH * 0.28]
    t = Table(data, colWidths=col_w, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE_COLOR]),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    return t


# ---------------------------------------------------------------------------
# Section builder helpers
# ---------------------------------------------------------------------------
def _section(story, title, styles, elements):
    """Wrap a section heading + content in KeepTogether to avoid orphan headers."""
    block = [
        HRFlowable(width=CONTENT_WIDTH, thickness=0.5, color=BORDER_COLOR, spaceAfter=4),
        Paragraph(title, styles["section_heading"]),
        Spacer(1, 4),
        *elements,
    ]
    story.append(KeepTogether(block[:3]))   # Keep heading glued to first element
    for el in block[3:]:
        story.append(el)


def _skill_list_section(story, title, skills, empty_text, styles):
    """Render a labelled skill list section."""
    elements = []
    tbl = _skills_table(skills, empty_text)
    if tbl:
        elements.append(tbl)
    else:
        elements.append(Paragraph(empty_text, styles["muted"]))
    _section(story, title, styles, elements)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------
def generate_report(
    score,
    category,
    skill_score,
    text_similarity,
    experience_score,
    matched,
    missing,
    suggestions,
    recommended_jobs,
    gap_analysis=None,
):
    """
    Generate the ATS analysis PDF and return its file path.

    gap_analysis: optional dict from analyze_resume_job_gap() containing
      partial_matches, prioritized_gaps, roadmap, and recommendations.
    """
    os.makedirs("reports", exist_ok=True)

    styles = _build_styles()

    # Build document with header/footer canvas callbacks
    pdf = SimpleDocTemplate(
        REPORT_FILE_PATH,
        pagesize=letter,
        rightMargin=RIGHT_MARGIN,
        leftMargin=LEFT_MARGIN,
        topMargin=TOP_MARGIN + 36,   # extra clearance for header bar
        bottomMargin=BOTTOM_MARGIN + 28,  # extra clearance for footer
        title=f"{BRAND_NAME} — ATS Analysis Report",
        author=BRAND_NAME,
        subject="ATS Resume Evaluation Report",
    )

    story = []

    # -----------------------------------------------------------------------
    # Cover block
    # -----------------------------------------------------------------------
    story.append(Paragraph(BRAND_NAME, styles["report_title"]))
    story.append(Paragraph(REPORT_SUBTITLE, styles["report_subtitle"]))
    story.append(Spacer(1, 10))

    # -----------------------------------------------------------------------
    # Score Summary
    # -----------------------------------------------------------------------
    _section(story, "ATS Score Summary", styles, [
        _score_table(score, category, skill_score, text_similarity, experience_score),
    ])

    # -----------------------------------------------------------------------
    # Matched Skills
    # -----------------------------------------------------------------------
    _skill_list_section(
        story,
        "Matched Skills",
        [format_skill(s) for s in (matched or [])],
        "No matched skills found.",
        styles,
    )

    # -----------------------------------------------------------------------
    # Missing Skills
    # -----------------------------------------------------------------------
    _skill_list_section(
        story,
        "Missing Skills",
        [format_skill(s) for s in (missing or [])],
        "No missing skills identified.",
        styles,
    )

    # -----------------------------------------------------------------------
    # Partial / Related Skills (from gap_analysis)
    # -----------------------------------------------------------------------
    partial_matches = (gap_analysis or {}).get("partial_matches", [])
    if partial_matches:
        tbl = _partial_skills_table(partial_matches)
        _section(story, "Partial / Related Skills", styles, [
            Paragraph(
                "These skills partially satisfy a requirement (50% credit applied).",
                styles["muted"],
            ),
            Spacer(1, 4),
            tbl,
        ])

    # -----------------------------------------------------------------------
    # Suggestions
    # -----------------------------------------------------------------------
    if suggestions:
        elements = []
        for sug in suggestions:
            elements.append(Paragraph(f"\u2022  {sug}", styles["bullet"]))
        _section(story, "Improvement Suggestions", styles, elements)

    # -----------------------------------------------------------------------
    # Gap Analysis Coverage
    # -----------------------------------------------------------------------
    coverage = (gap_analysis or {}).get("skill_coverage")
    if coverage and coverage.get("total_requirements", 0) > 0:
        cov_data = [
            ["Coverage Metric", "Value"],
            ["Total Requirements", str(coverage["total_requirements"])],
            ["Exact Matches", str(coverage["exact_matches"])],
            ["Partial Matches", str(coverage["partial_matches"])],
            ["Missing", str(coverage["missing"])],
            ["Effective Coverage", f'{coverage["coverage_percentage"]}%'],
        ]
        col_w = [2.4 * inch, 1.8 * inch]
        t = Table(cov_data, colWidths=col_w, hAlign="LEFT")
        t.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_COLOR),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE_COLOR]),
        ]))
        _section(story, "Gap Analysis Coverage", styles, [t])

    # -----------------------------------------------------------------------
    # Prioritized Improvement Roadmap
    # -----------------------------------------------------------------------
    roadmap = (gap_analysis or {}).get("roadmap", {})
    immediate = roadmap.get("immediate", [])
    next_gaps = roadmap.get("next", [])
    optional_gaps = roadmap.get("optional", [])

    if immediate or next_gaps or optional_gaps:
        story.append(HRFlowable(width=CONTENT_WIDTH, thickness=0.5, color=BORDER_COLOR, spaceAfter=4))
        story.append(Paragraph("Resume Improvement Roadmap", styles["section_heading"]))

        if immediate:
            story.append(Paragraph(
                "<b>Immediate Priorities</b> — High impact gaps to address first",
                styles["muted"],
            ))
            story.append(Spacer(1, 3))
            tbl = _roadmap_table(immediate, "HIGH", ACCENT_DANGER, colors.white)
            if tbl:
                story.append(tbl)
            story.append(Spacer(1, 8))

        if next_gaps:
            story.append(Paragraph(
                "<b>Next Priorities</b> — Medium impact gaps",
                styles["muted"],
            ))
            story.append(Spacer(1, 3))
            tbl = _roadmap_table(next_gaps, "MEDIUM", ACCENT_WARNING, colors.white)
            if tbl:
                story.append(tbl)
            story.append(Spacer(1, 8))

        if optional_gaps:
            story.append(Paragraph(
                "<b>Optional Enhancements</b> — Nice-to-have improvements",
                styles["muted"],
            ))
            story.append(Spacer(1, 3))
            tbl = _roadmap_table(optional_gaps, "LOW", SURFACE_ALT, TEXT_COLOR)
            if tbl:
                story.append(tbl)
            story.append(Spacer(1, 8))

    # -----------------------------------------------------------------------
    # AI Roadmap (optional)
    # -----------------------------------------------------------------------
    ai_roadmap = (gap_analysis or {}).get("ai_roadmap")
    if ai_roadmap and isinstance(ai_roadmap, str) and ai_roadmap.strip():
        ai_lines = [line.strip() for line in ai_roadmap.strip().splitlines() if line.strip()]
        ai_elements = [
            Paragraph(
                "AI-generated improvement guidance (supplementary only — does not affect ATS score):",
                styles["muted"],
            ),
            Spacer(1, 4),
            *[Paragraph(line, styles["ai_body"]) for line in ai_lines],
        ]
        _section(story, "AI Improvement Guidance", styles, ai_elements)

    # -----------------------------------------------------------------------
    # Recommended Jobs
    # -----------------------------------------------------------------------
    tbl = _jobs_table(recommended_jobs)
    if tbl:
        _section(story, "Recommended Job Roles", styles, [tbl])
    else:
        _section(story, "Recommended Job Roles", styles, [
            Paragraph("No job role recommendations available.", styles["muted"]),
        ])

    # -----------------------------------------------------------------------
    # Footer note
    # -----------------------------------------------------------------------
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width=CONTENT_WIDTH, thickness=0.5, color=BORDER_COLOR))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"<i>This report was generated by <b>{BRAND_NAME}</b>. "
        "ATS scores are deterministic and are not modified by AI features. "
        "Score formula: 50% Skill Match + 30% Text Similarity + 20% Experience Match.</i>",
        styles["muted"],
    ))

    # -----------------------------------------------------------------------
    # Build PDF
    # -----------------------------------------------------------------------
    pdf.build(story, onFirstPage=_draw_header_footer, onLaterPages=_draw_header_footer)

    return REPORT_FILE_PATH